### ISSUE TITLE
running with v2.2

### ISSUE THREAD

**Issue by ic1062** [lipan6461188/AlphaFold-StepByStep#1]
Hello, I am running AF v2.2 in a docker container:

Is your step-by-step compatible with v2.2?
Do I need to run step-by-step in my v2.2 container?

Thanks for making this available.

**Comment by lipan6461188** [comment]
Yes, now it support for v2.2. You must run this step-by-step protocol in the same environment with AlphaFold (in docker container).

**Comment by ic1062** [comment]
Thank you.
